# Generated by Django 5.1.1 on 2025-05-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_event_status'),
        ('app', '0005_favorite'),
    ]

    operations = [
    ]
